// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTKKRwHzEDmNOI-EIlkMEdjPK-aILUng',
    appId: '1:124387558166:web:272340e1b568d8621d8637',
    messagingSenderId: '124387558166',
    projectId: 'fir-auth-app-9ac44',
    authDomain: 'fir-auth-app-9ac44.firebaseapp.com',
    storageBucket: 'fir-auth-app-9ac44.firebasestorage.app',
    measurementId: 'G-YL1L3YG52T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRgtIAdo7n-y0r0nHGesMMuI9EmfOEVe0',
    appId: '1:124387558166:android:5d43c35333ba1d0e1d8637',
    messagingSenderId: '124387558166',
    projectId: 'fir-auth-app-9ac44',
    storageBucket: 'fir-auth-app-9ac44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkyXl9vDH9gp5XTLu0mXYQYvOmTOdLYx0',
    appId: '1:124387558166:ios:94b0973995f3a78e1d8637',
    messagingSenderId: '124387558166',
    projectId: 'fir-auth-app-9ac44',
    storageBucket: 'fir-auth-app-9ac44.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkyXl9vDH9gp5XTLu0mXYQYvOmTOdLYx0',
    appId: '1:124387558166:ios:94b0973995f3a78e1d8637',
    messagingSenderId: '124387558166',
    projectId: 'fir-auth-app-9ac44',
    storageBucket: 'fir-auth-app-9ac44.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJTKKRwHzEDmNOI-EIlkMEdjPK-aILUng',
    appId: '1:124387558166:web:1a47300605a72e001d8637',
    messagingSenderId: '124387558166',
    projectId: 'fir-auth-app-9ac44',
    authDomain: 'fir-auth-app-9ac44.firebaseapp.com',
    storageBucket: 'fir-auth-app-9ac44.firebasestorage.app',
    measurementId: 'G-PHZBTS6HFE',
  );
}
